config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :locations do
    resources :rooms
  end
  
  resources :students do
    resources :courses
  end

  resources :courses do
    resources :students
  end

  resources :home


  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses
  # has_many :courses, through: :enrolments
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    # binding.pry
    if params[:course_id] then
      course = Course.find(params[:course_id])
      @students = course.students
      @course_id = course.id
    else
      @students = Student.all
    end

  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    if params[:course_id]
      @course = Course.find(params[:course_id])
      @student = @course.students.new
    else
      @student = Student.new
    end
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    if params[:course_id]
      course = Course.find(params[:course_id])
      @student.courses << course
    end
    # @student.courses = "hyehyhdd";
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:concession, :name, :email, :cabin, :paid)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% if params[:course_id].present? %>

  <%= form_for([course, student]) do |f| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :concession %>
      <%= f.text_field :concession %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>



    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :cabin %>
      <%= f.select(:cabin,['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7',"D8", "D9", "A1", "A2", "A3", "A4", "A5", "C1.1", "C1.2", "C2.1", "C2.2"]) %>
    </div>

    <div class="field">
      <%= f.label :paid %>
      <%= f.select(:paid,['Yes', 'No']) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>

  <%= form_for(student) do |f| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :concession %>
      <%= f.text_field :concession %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>



    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :cabin %>
      <%= f.select(:cabin,['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7',"D8", "D9", "A1", "A2", "A3", "A4", "A5", "C1.1", "C1.2", "C2.1", "C2.2"]) %>
    </div>

    <div class="field">
      <%= f.label :paid %>
      <%= f.select(:paid,['Yes', 'No']) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Concession</th>
      <th>Name</th>
      <th>Email</th>
      <th>Cabin</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.concession %></td>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.cabin %></td>
        <td><%= student.paid %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if @course_id %>
<%= link_to 'New Student', new_course_student_path(course_id: @course_id) %>
<%else%>
<%= link_to 'New Student', new_student_path %>
<%end%>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student, course: @course %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concession:</strong>
  <%= @student.concession %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Cabin:</strong>
  <%= @student.cabin %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @student.paid %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>