config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :locations do
    resources :rooms
  end
  
  resources :students do
    resources :courses
  end

  resources :courses do
    resources :students
  end

  resources :home


  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  # has_many :rooms
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :rooms, :availability)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rooms %>
    <%= f.text_field :rooms %>
  </div>

  <div class="field">
    <%= f.label :availability %>
    <%= f.text_field :availability %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rooms</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to rooms_path do %>
              <%= location.name %>
            <% end %></td>
        <td><%= location.rooms %></td>
        <td><%= location.availability %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @location.rooms %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @location.availability %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>
<%= link_to 'New Room', new_room_path(@location) %>